name: first file

on: [push]

jobs:
  first_job_id:
     name: first job
     runs-on: ubuntu_latest
     steps:
        - name: download file
          uses: actions/workflows@v4
          run: |
           echo "first run command"
     
