name: first file

on: [push]

jobs:
  first_job_id:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download java
        uses: actions/setup-java@v4
        
      - name: Run command
        run: |
          echo "print java version"
          java -version
